%YAML:1.0
---
#
# Common detection parameters that apply to both detection and calibration modes.
marker_detection:
   camera_id: 0
   frame_width_pixels: 640
   frame_height_pixels: 480
   frame_rate_fps: 30
   show_rejected_markers: 0
#
# Parameters specific to line follower marker.
line_follower_marker:
   marker_side_meters: 4.7200001776218414e-02
   marker_id: 5
   marker_dictionary_id: 17
#
# Parameters specific to board markers.
board_markers:
   marker_side_meters: 3.9999999105930328e-02
   marker_seperation_meters_x: 1.7399999499320984e-01
   marker_seperation_meters_y: 1.1100000143051147e-01
   marker_ids: [ 0, 1, 2, 3 ]
   marker_dictionary_id: 0
#
# Parameters specific to track specifications.
track_selection: 1
#
line_track:
   point1:
      x_meters: 3.00e-02
      y_meters: 3.00e-02
   point2:
      x_meters: 14.4e-02
      y_meters: 3.00e-02
#
round_track:
   center:
      x_meters: 0.
      y_meters: 0.
   major_axis_meters: 0.
   minor_axis_meters: 0.
#
# Parameters specific to camera calibration.
camera_calibration:
   marker_side_meters: 2.1999999880790710e-02
   square_side_meters: 2.9999999329447746e-02
   squares_quantity_x: 8
   squares_quantity_y: 6
   marker_dictionary_id: 0
   camera_matrix: !!opencv-matrix
      rows: 3
      cols: 3
      dt: d
      data: [ 5.1706357226477041e+02, 0., 3.1759414549376646e+02, 0.,
          5.1860692972536117e+02, 2.3909934290274310e+02, 0., 0., 1. ]
   distortion_coefficients: !!opencv-matrix
      rows: 1
      cols: 5
      dt: d
      data: [ 2.0544025320746187e-02, 5.3760907532437463e-01,
          -9.2310469460404746e-04, 2.4684101075773124e-03,
          -1.4802296558637367e+00 ]
