%YAML:1.0
---
#
# Common detection parameters that apply to both detection and calibration modes.
marker_detection:
   camera_id: 0
   show_rejected_markers: 0
#
# Parameters specific to line follower marker.
line_follower_marker:
   marker_side_meters: 4.7200001776218414e-02
   marker_id: 5
   marker_dictionary_id: 17
#
# Parameters specific to board markers.
board_markers:
   marker_side_meters: 9.4999998807907104e-02
   marker_seperation_meters_x: 7.4699997901916504e-01
   marker_seperation_meters_y: 4.3599998950958252e-01
   marker_ids: [ 0, 1, 2, 3 ]
   marker_dictionary_id: 0
#
# Parameters specific to track specifications.
track_selection: 1
#
line_track:
   point1:
      x_meters: 0.
      y_meters: 0.
   point2:
      x_meters: 0.
      y_meters: 0.
#
round_track:
   center:
      x_meters: 0.
      y_meters: 0.
   major_axis_meters: 0.
   minor_axis_meters: 0.
#
# Parameters specific to camera calibration.
camera_calibration:
   marker_side_meters: 2.1999999880790710e-02
   square_side_meters: 2.9999999329447746e-02
   squares_quantity_x: 8
   squares_quantity_y: 6
   marker_dictionary_id: 0
   camera_matrix: !!opencv-matrix
      rows: 3
      cols: 3
      dt: d
      data: [ 6.3907596835249956e+02, 0., 3.1218831096372253e+02, 0.,
          6.4002187939248392e+02, 2.3395702872485549e+02, 0., 0., 1. ]
   distortion_coefficients: !!opencv-matrix
      rows: 1
      cols: 5
      dt: d
      data: [ 7.1561765707709862e-02, -9.4377352823716926e-02,
          -7.9134037658199746e-03, -1.7624553999958284e-04,
          -1.0534280228092834e+00 ]
