%YAML:1.0
---
marker_detection:
   input_source_path: none
   camera_id: 0
   marker_dictionary: 0
   marker_side_meters: 2.1999999880790710e-02
board_markers:
   marker_side_meters: 2.10e-02
   marker_seperation_meters_x: 20.00e-02
   marker_seperation_meters_y: 14.00e-02
   marker_dictionary_id: 0
   marker_ids: [ 0, 1, 2, 3 ]
camera_calibration:
   squares_quantity_x: 8
   squares_quantity_y: 6
   square_side_meters: 2.9999999329447746e-02
   camera_matrix: !!opencv-matrix
      rows: 3
      cols: 3
      dt: f
      data: [ 5.14758362e+02, 0., 3.08533203e+02, 0., 5.14997742e+02,
          2.49487762e+02, 0., 0., 1. ]
   distortion_coefficients: !!opencv-matrix
      rows: 1
      cols: 5
      dt: f
      data: [ -8.24871473e-03, 6.68980122e-01, 3.13996430e-03,
          -6.13448117e-03, -1.93881428e+00 ]
