%YAML:1.0
marker_detection:
  input_file_path: none
  camera_id: 0
  marker_dictionary: 0
  marker_side_meters: 0.1

camera_calibration:
  camera_matrix: !!opencv-matrix
    rows: 3
    cols: 3
    dt: d
    data: [ 0., 0., 0., 0., 0., 0., 0., 0., 0. ]

  distortion_coefficients: !!opencv-matrix
    rows: 5
    cols: 1
    dt: d
    data: [ 0., 0., 0., 0., 0. ]
