#pragma once

// TODO: Define error codes and implement error handling
enum class Error {

  CANNOT_OPEN_FILE = 401,
  MISSING_MARKER_DETECTION_CONFIG = 402,
  MISSING_LINE_FOLLOWER_MARKER_CONFIG = 403,
  MISSING_BOARD_MARKERS_CONFIG = 404,
  MISSING_CALIBRATION_CONFIG = 405,
  INVALID_TRACK_OPTION = 406,
  MISSING_LINE_TRACK_CONFIG = 407,
  MISSING_ROUND_TRACK_CONFIG = 408

};
